baseurl = "https://www.olblak.com"
title = "Olblak"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "olblak"

[params]
    author = "Olblak"
    info = "Infra Developer"
    description = "Me"
    keywords = "blog,developer,personal,infra"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "FOSS Aficionado"

    hidecredits = false
    hidecopyright = false
    hidefooter = false

    rtl = false

    math = false
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/olblak"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/0lblak/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/overnin/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/blogs/"
    
[[menu.main]]
    name = "About"
    weight = 2
    url  = "/about"

[[menu.main]]
    name = "Contact"
    weight = 3
    url  = "/contact"
